# Generated by Django 3.1.4 on 2020-12-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='user_type',
            field=models.CharField(choices=[('V', 'Vendor'), ('U', 'User')], default='U', max_length=2),
        ),
    ]
