# Generated by Django 3.1.4 on 2020-12-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_useraccount_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_type',
            field=models.CharField(choices=[('V', 'Vendor'), ('U', 'User'), ('A', 'Admin')], default='U', max_length=2),
        ),
    ]
